baseURL = "https://jaigansa.github.io/jaidocs/"
languageCode = 'en-us'
title = 'Jaidoc'
theme = 'jaidoc'
canonifyURLs = true

disableKinds = ["taxonomy", "term", "sitemap"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineChars = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = "monokai"
    tabWidth = 4
    withCopyButton = false

ignoreLogs = ["warning-goldmark-raw-html"]

[build]
  writeStats = true
  renderToMemory = false

[privacy]
  [privacy.instagram]
    disable = false
    simple = true
